REQUEST_COUNT = 0
SUCCESS_COUNT = 0
ERROR_REQUEST_COUNT = 0
SLOW_REQUEST_COUNT = 0

ERROR_COUNT = 0
TIMEOUT_COUNT = 0

AVG_DURATION = 0
LAST_DURATION = 0

LAST_TOKENS = 0
TOKENS_PER_SEC = 0

LAST_ERROR = None
LAST_ERROR_TIME = None
LAST_ERROR_REQUEST = None

LAST_SUCCESS_REQUEST = None
LAST_SUCCESS_TIME = None

LAST_EVENT = None
LAST_EVENT_TIME = None

LAST_TOOL_USED = None
LAST_TOOL_ARGS = None
LAST_TOOL_TIME = None

LAST_CRASH_TIME = None
LAST_CRASH_REQUEST = None
